name: Docker ECR Build and Push

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      # Checkout the repository to the runner
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build the Docker image
      - name: Build Docker image
        run: |
          # Define the repository URL
          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/mevton-labs/mevton-ton-validator:${{ github.sha }}"

          # Build the Docker image
          docker build -t $IMAGE_URI .

      # Push the Docker image to Amazon ECR
      - name: Push Docker image to ECR
        run: |
          # Define the repository URL
          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/mevton-labs/mevton-ton-validator:${{ github.sha }}"

          # Push the image to the ECR repository
          docker push $IMAGE_URI